version: '3.5'
services:
  web:
    container_name: odoo-web
    image: odoo:15
    depends_on:
      - db
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - odoo-web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    # command:
    #   odoo -r odoo -w odoo -i addons -d odoo
  pgadmin:
    container_name: odoo-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - odoo-pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: odoo-db
    image: postgres:12.8
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web:
  odoo-db:
  odoo-pgadmin: